version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=away-days
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://away-days:password@postgres:5432/away-days?
